# Base Docker Compose file for all WordPress websites on EC2
# This matches the Fargate task definition configuration
#
# Environment variables that must be set:
# - FPM_IMAGE: Full ECR URI for the FPM image
# - NGINX_IMAGE: Full ECR URI for the NGINX image
# - WORDPRESS_DB_HOST: Database endpoint (e.g., db-instance.xxxxx.region.rds.amazonaws.com:3306)
# - WORDPRESS_DB_NAME: Database name (website name)
# - WORDPRESS_DB_USER: Database username
# - WORDPRESS_DB_PASSWORD: Database password
# - WEBSITE_PORT: External port to expose (e.g., 8001, 8002, etc.)

services:
  fpm:
    image: ${FPM_IMAGE}
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - ./wp-data:/var/www/html
    healthcheck:
      test: ["CMD-SHELL", "SCRIPT_NAME=/healthcheck.php SCRIPT_FILENAME=/opt/healthcheck.php cgi-fcgi -bind -connect localhost:9000 | grep -q 'X-Powered-By: PHP' || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s

  nginx:
    image: ${NGINX_IMAGE}
    restart: unless-stopped
    ports:
      - "${WEBSITE_PORT}:80"
    environment:
      FASTCGI_PASS: fpm:9000
    volumes:
      - ./wp-data:/var/www/html
    depends_on:
      fpm:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
